name: 'Build Docs'

on: push
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running!"
      - run: echo "npm run build"