node {

   def commit_id

  try {
  //  stage('Preparation') {
  //    checkout scm
  //    sh "git rev-parse --short HEAD > .git/commit-id"                        
  //    commit_id = readFile('.git/commit-id').trim()
  //  }
  //  stage('test') {
  //    nodejs(nodeJSInstallationName: 'nodejs') {
  //      sh 'npm install --legacy-peer-deps'
  //      sh 'npm test'
  //    }
  //  }
   stage('update docs') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'git add .'
        sh 'git stash'
       sh 'git switch main'
       sh 'npm install --legacy-peer-deps'
      //  sh 'git commit -am "Jenkins updating docs folder for github pages"'
       sh 'npm run build'
       sh 'ls'
       sh 'git status'
       sh 'git config --global user.email "islandhopper152@gmail.com"'
       sh 'git config --global user.name "williamowen65"'
       sh 'git remote -v'
       sh 'git branch'
       sh 'git commit -am "Jenkins updating docs folder for github pages"'
       sh 'git push -u origin main --force'

     }
   } 





  } catch(e){
        // mark build as failed
    currentBuild.result = "FAILURE";

    // send slack notification
    slackSend (channel:"#outside-games",color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}/console)")

    // throw the error
    throw e;
  }
    slackSend (channel: "#outside-games", color: '#FF0000', message: "SUCCESS 🎈: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' ('islandhopper152/read_voices:${commit_id}')")
}