node {

   def commit_id

  try {
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --legacy-peer-deps'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("islandhopper152/og:${commit_id}", '.').push()
     }
   } 


   stage("deploy to port 8083") {
      sh 'docker stop og || true'
      sh "docker run -p 8083:8080 --name og --rm -d islandhopper152/og:${commit_id}"
   }


  } catch(e){
        // mark build as failed
    currentBuild.result = "FAILURE";

    // send slack notification
    slackSend (channel:"#outside-games",color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}/console)")

    // throw the error
    throw e;
  }
    slackSend (channel: "#outside-games", color: '#FF0000', message: "SUCCESS 🎈: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' ('islandhopper152/read_voices:${commit_id}')")
}